// 문항 자료. 형식과 규칙은 PRD.md 5절을 따릅니다.
const QUESTIONS = [
  // ===== 한국사 =====
  {
    id: "kh-01",
    category: "한국사",
    difficulty: "쉬움",
    question: "1443년에 훈민정음을 창제한 조선의 왕은?",
    choices: ["세종", "태종", "세조", "성종"],
    answer: "세종",
    explanation: "세종은 1443년 12월 훈민정음을 창제하고 1446년에 반포했다.",
    source: { title: "한글 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0061508" },
  },
  {
    id: "kh-02",
    category: "한국사",
    difficulty: "쉬움",
    question: "918년에 고려를 건국한 인물은?",
    choices: ["왕건", "궁예", "견훤", "김부"],
    answer: "왕건",
    explanation: "왕건은 918년 고려를 세우고 936년 후삼국을 통합했다.",
    source: { title: "고려 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0003424" },
  },
  {
    id: "kh-03",
    category: "한국사",
    difficulty: "쉬움",
    question: "1592년 한산도 앞바다에서 학익진으로 일본 수군을 크게 무찌른 조선의 장수는?",
    choices: ["이순신", "권율", "김시민", "곽재우"],
    answer: "이순신",
    explanation: "전라좌수사 이순신은 한산도대첩에서 학익진을 펼쳐 일본 수군의 주력을 무찔렀다.",
    source: { title: "한산도대첩 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0061676" },
  },
  {
    id: "kh-04",
    category: "한국사",
    difficulty: "보통",
    question: "고려 후기의 승려 일연이 고조선부터 후삼국까지의 이야기를 모아 편찬한 역사서는?",
    choices: ["삼국유사", "삼국사기", "고려사", "동국통감"],
    answer: "삼국유사",
    explanation: "『삼국유사』는 1281년(충렬왕 7)경 고려 승려 일연이 편찬한 역사서다.",
    source: { title: "삼국유사 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0026482" },
  },
  {
    id: "kh-05",
    category: "한국사",
    difficulty: "쉬움",
    question: "3·1 운동이 일어난 해는?",
    choices: ["1919년", "1910년", "1926년", "1945년"],
    answer: "1919년",
    explanation: "3·1 운동은 1919년 3월 1일을 기해 일어난 거족적인 독립만세운동이다.",
    source: { title: "3·1운동 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0026772" },
  },
  {
    id: "kh-06",
    category: "한국사",
    difficulty: "보통",
    question: "1919년 4월 11일에 수립된 대한민국 임시정부가 있던 도시는?",
    choices: ["상하이", "도쿄", "베이징", "블라디보스토크"],
    answer: "상하이",
    explanation: "임시정부는 1919년 4월 11일 중국 상하이에서 수립되었다(정부 기념일은 2019년부터 4월 11일로 정함).",
    source: { title: "대한민국 임시정부 수립 기념일 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0080590" },
  },
  {
    id: "kh-07",
    category: "한국사",
    difficulty: "어려움",
    question: "조선의 기본 법전인 『경국대전』을 완성해 시행한 왕은?",
    choices: ["성종", "세종", "태조", "영조"],
    answer: "성종",
    explanation: "성종은 즉위 후 『경국대전』을 다시 수정해 1471년 1월 1일부터 시행했다.",
    source: { title: "경국대전 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0002296" },
  },
  {
    id: "kh-08",
    category: "한국사",
    difficulty: "보통",
    question: "660년 황산벌에서 5,000명의 결사대를 이끌고 신라군에 맞선 백제의 장군은?",
    choices: ["계백", "김유신", "을지문덕", "관창"],
    answer: "계백",
    explanation: "의자왕은 장군 계백에게 결사대 5,000명을 조직해 신라군을 막게 했다.",
    source: { title: "황산벌전투 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0065183" },
  },
  {
    id: "kh-09",
    category: "한국사",
    difficulty: "보통",
    question: "몸이 작아 '녹두장군'이라 불린 동학 농민 운동의 지도자는?",
    choices: ["전봉준", "최제우", "김옥균", "홍경래"],
    answer: "전봉준",
    explanation: "전봉준은 몸이 왜소해 녹두라 불렸고, 1894년 고부에서 농민군을 이끌고 봉기했다.",
    source: { title: "전봉준 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0049437" },
  },
  {
    id: "kh-10",
    category: "한국사",
    difficulty: "보통",
    question: "1377년 청주 흥덕사에서 금속활자로 인쇄되어 2001년 유네스코 세계기록유산에 등재된 책은?",
    choices: ["직지심체요절", "팔만대장경", "무구정광대다라니경", "조선왕조실록"],
    answer: "직지심체요절",
    explanation: "『직지』는 현존하는 가장 오래된 금속활자 인쇄물로 2001년 세계기록유산이 되었다.",
    source: { title: "불조직지심체요절 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0025035" },
  },
  {
    id: "kh-11",
    category: "한국사",
    difficulty: "보통",
    question: "1907년 네덜란드 헤이그의 제2회 만국평화회의에 이상설·이준·이위종을 특사로 보내 을사늑약의 부당함을 알리려 한 대한제국의 황제는?",
    choices: ["고종", "순종", "철종", "헌종"],
    answer: "고종",
    explanation: "고종은 1907년 헤이그 만국평화회의에 이상설·이준·이위종을 보내 을사늑약이 무효임을 국제 사회에 호소하려 했다.",
    source: { title: "헤이그 특사 사건 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0063241" },
  },

  // ===== 세계지리 =====
  {
    id: "wg-01",
    category: "세계지리",
    difficulty: "쉬움",
    question: "현재 국토 면적을 기준으로 세계에서 가장 넓은 나라는?",
    choices: ["러시아", "캐나다", "중국", "미국"],
    answer: "러시아",
    explanation: "러시아는 세계에서 가장 넓은 나라로, 지구 육지의 약 10분의 1을 차지한다.",
    source: { title: "Russia - National Geographic Kids", url: "https://kids.nationalgeographic.com/geography/countries/article/russia" },
  },
  {
    id: "wg-02",
    category: "세계지리",
    difficulty: "보통",
    question: "유엔(UN) 추계에 따르면 2023년에 중국을 제치고 인구가 가장 많은 나라가 된 곳은?",
    choices: ["인도", "인도네시아", "미국", "파키스탄"],
    answer: "인도",
    explanation: "유엔은 2023년 4월 말 인도 인구가 약 14억 2,578만 명으로 중국을 넘어선다고 밝혔다.",
    source: { title: "India poised to become world's most populous nation - UN News (2023)", url: "https://news.un.org/en/story/2023/04/1135967" },
  },
  {
    id: "wg-03",
    category: "세계지리",
    difficulty: "보통",
    question: "오스트레일리아의 수도는?",
    choices: ["캔버라", "시드니", "멜버른", "브리즈번"],
    answer: "캔버라",
    explanation: "오스트레일리아의 수도는 캔버라이며, 가장 큰 도시인 시드니와는 다르다.",
    source: { title: "Australia - National Geographic Kids", url: "https://kids.nationalgeographic.com/geography/countries/article/australia" },
  },
  {
    id: "wg-04",
    category: "세계지리",
    difficulty: "보통",
    question: "1960년에 새 수도로 문을 연 브라질의 수도는?",
    choices: ["브라질리아", "리우데자네이루", "상파울루", "살바도르"],
    answer: "브라질리아",
    explanation: "브라질리아는 1960년 4월 문을 연 계획도시로, 해안에 있던 옛 수도를 대신했다.",
    source: { title: "Brasília, Brazil - NASA Earth Observatory", url: "https://science.nasa.gov/earth/earth-observatory/brasilia-brazil-43743" },
  },
  {
    id: "wg-05",
    category: "세계지리",
    difficulty: "보통",
    question: "에베레스트산 정상을 국경선이 지나는 두 나라는?",
    choices: ["네팔과 중국", "네팔과 인도", "인도와 파키스탄", "부탄과 중국"],
    answer: "네팔과 중국",
    explanation: "네팔과 중국(티베트)을 가르는 국경선이 에베레스트산 정상을 지난다.",
    source: { title: "Remeasuring Mount Everest - National Geographic", url: "https://www.nationalgeographic.com/science/article/remeasuring-mount-everest-the-worlds-tallest-mountain" },
  },
  {
    id: "wg-06",
    category: "세계지리",
    difficulty: "쉬움",
    question: "사하라 사막이 있는 대륙은?",
    choices: ["아프리카", "아시아", "오세아니아", "남아메리카"],
    answer: "아프리카",
    explanation: "사하라 사막은 아프리카 북부에 있으며, 세계에서 가장 넓은 더운 사막이다.",
    source: { title: "Deserts, facts and information - National Geographic", url: "https://www.nationalgeographic.com/environment/article/deserts" },
  },
  {
    id: "wg-07",
    category: "세계지리",
    difficulty: "쉬움",
    question: "면적을 기준으로 세계에서 가장 넓은 대양은?",
    choices: ["태평양", "대서양", "인도양", "북극해"],
    answer: "태평양",
    explanation: "미국 해양대기청(NOAA)에 따르면 태평양은 세계의 대양 가운데 가장 넓다.",
    source: { title: "What is the biggest ocean? - NOAA National Ocean Service", url: "https://oceanservice.noaa.gov/facts/biggestocean.html" },
  },
  {
    id: "wg-08",
    category: "세계지리",
    difficulty: "보통",
    question: "1884년 국제 자오선 회의에서 경도 0°의 기준(본초 자오선)으로 정한 곳은?",
    choices: ["영국 그리니치", "프랑스 파리", "미국 워싱턴 D.C.", "이탈리아 로마"],
    answer: "영국 그리니치",
    explanation: "1884년 회의에서 그리니치 천문대를 지나는 자오선이 세계의 본초 자오선이 되었다.",
    source: { title: "What is the Prime Meridian, and why is it in Greenwich? - Royal Museums Greenwich", url: "https://www.rmg.co.uk/stories/time/what-prime-meridian-why-it-greenwich" },
  },
  {
    id: "wg-09",
    category: "세계지리",
    difficulty: "보통",
    question: "대서양과 지중해를 잇고, 에스파냐와 모로코 사이에 있는 해협은?",
    choices: ["지브롤터 해협", "보스포루스 해협", "호르무즈 해협", "말라카 해협"],
    answer: "지브롤터 해협",
    explanation: "지브롤터 해협은 대서양과 지중해를 잇고 유럽(에스파냐)과 아프리카(모로코)를 가른다.",
    source: { title: "The Strait of Gibraltar Connects the Atlantic to the Mediterranean - NASA", url: "https://www.nasa.gov/image-article/strait-of-gibraltar-connects-atlantic-mediterranean/" },
  },
  {
    id: "wg-10",
    category: "세계지리",
    difficulty: "쉬움",
    question: "지중해와 홍해를 잇는 수에즈 운하가 있는 나라는?",
    choices: ["이집트", "튀르키예", "파나마", "사우디아라비아"],
    answer: "이집트",
    explanation: "수에즈 운하는 이집트에 있으며 1869년에 개통되어 지중해와 홍해를 잇는다.",
    source: { title: "Canal History - Suez Canal Authority", url: "https://www.suezcanal.gov.eg/English/About/SuezCanal/Pages/CanalHistory.aspx" },
  },
  {
    id: "wg-11",
    category: "세계지리",
    difficulty: "보통",
    question: "아프리카 동북부를 북쪽으로 흐르는 나일강이 이집트에서 흘러 들어가는 바다는?",
    choices: ["지중해", "홍해", "인도양", "카스피해"],
    answer: "지중해",
    explanation: "나일강은 이집트 북부에서 삼각주를 이룬 뒤 지중해로 흘러 들어간다.",
    source: { title: "Nile River - National Geographic Education", url: "https://education.nationalgeographic.org/resource/nile-river/" },
  },

  // ===== 과학 =====
  {
    id: "sc-01",
    category: "과학",
    difficulty: "쉬움",
    question: "원소 기호가 Fe인 원소는?",
    choices: ["철", "불소", "납", "인"],
    answer: "철",
    explanation: "Fe는 철(iron)의 원소 기호이며, 철의 원자 번호는 26이다.",
    source: { title: "Iron - Royal Society of Chemistry Periodic Table", url: "https://periodic-table.rsc.org/element/26/iron" },
  },
  {
    id: "sc-02",
    category: "과학",
    difficulty: "쉬움",
    question: "원자 번호가 1인 원소는?",
    choices: ["수소", "헬륨", "산소", "탄소"],
    answer: "수소",
    explanation: "수소(H)는 원자 번호가 1인 원소다.",
    source: { title: "Hydrogen - Royal Society of Chemistry Periodic Table", url: "https://periodic-table.rsc.org/element/1/hydrogen" },
  },
  {
    id: "sc-03",
    category: "과학",
    difficulty: "쉬움",
    question: "태양과의 거리를 기준으로, 태양계 행성 가운데 태양에 가장 가까운 행성은?",
    choices: ["수성", "금성", "지구", "화성"],
    answer: "수성",
    explanation: "NASA에 따르면 수성은 태양계에서 가장 작고 태양에 가장 가까운 행성이다.",
    source: { title: "Mercury Facts - NASA Science", url: "https://science.nasa.gov/mercury/facts/" },
  },
  {
    id: "sc-04",
    category: "과학",
    difficulty: "쉬움",
    question: "식물 세포에서 광합성을 맡는 세포 소기관은?",
    choices: ["엽록체", "미토콘드리아", "리보솜", "골지체"],
    answer: "엽록체",
    explanation: "엽록체는 광합성을 맡는 세포 소기관이다.",
    source: { title: "Chloroplasts and Other Plastids - The Cell (NCBI Bookshelf)", url: "https://www.ncbi.nlm.nih.gov/books/NBK9905/" },
  },
  {
    id: "sc-05",
    category: "과학",
    difficulty: "보통",
    question: "1953년 DNA의 이중 나선 구조를 밝힌 과학자들은?",
    choices: ["왓슨과 크릭", "멘델과 다윈", "퀴리 부부", "파스퇴르와 코흐"],
    answer: "왓슨과 크릭",
    explanation: "제임스 왓슨과 프랜시스 크릭이 1953년 DNA의 이중 나선 구조를 발표했다.",
    source: { title: "1953: DNA Double Helix - National Human Genome Research Institute", url: "https://www.genome.gov/25520255/online-education-kit-1953-dna-double-helix" },
  },
  {
    id: "sc-06",
    category: "과학",
    difficulty: "쉬움",
    question: "1905년 논문에서 질량과 에너지의 관계(E=mc²)를 이끌어 낸 과학자는?",
    choices: ["아인슈타인", "뉴턴", "보어", "맥스웰"],
    answer: "아인슈타인",
    explanation: "아인슈타인은 1905년 9월 특수 상대성 이론의 결과로 E=mc²를 이끌어 냈다.",
    source: { title: "September 1905: Energy and Mass are Equivalent - American Physical Society", url: "https://www.aps.org/apsnews/2005/04/september-1905-energy-mass-equivalent" },
  },
  {
    id: "sc-07",
    category: "과학",
    difficulty: "보통",
    question: "공기를 이루는 비율을 기준으로, 공기에 가장 많이 들어 있는 기체는?",
    choices: ["질소", "산소", "아르곤", "이산화 탄소"],
    answer: "질소",
    explanation: "NASA에 따르면 공기는 질소 78%, 산소 21%에 약간의 다른 기체가 섞여 있다.",
    source: { title: "Air Properties Definitions - NASA Glenn Research Center", url: "https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/air-properties-definitions/" },
  },
  {
    id: "sc-08",
    category: "과학",
    difficulty: "보통",
    question: "1928년 푸른곰팡이에서 페니실린을 발견한 과학자는?",
    choices: ["알렉산더 플레밍", "루이 파스퇴르", "로베르트 코흐", "에드워드 제너"],
    answer: "알렉산더 플레밍",
    explanation: "플레밍은 1928년 푸른곰팡이 주변에서 세균이 자라지 않는 것을 보고 페니실린을 발견했다.",
    source: { title: "The Discovery of Penicillin—New Insights After More Than 75 Years of Clinical Use (PMC)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5403050/" },
  },
  {
    id: "sc-09",
    category: "과학",
    difficulty: "보통",
    question: "'한 물체가 다른 물체에 힘을 가하면, 다른 물체도 크기가 같고 방향이 반대인 힘을 가한다'는 법칙은?",
    choices: ["뉴턴의 운동 제3법칙", "뉴턴의 운동 제1법칙", "뉴턴의 운동 제2법칙", "만유인력의 법칙"],
    answer: "뉴턴의 운동 제3법칙",
    explanation: "뉴턴의 운동 제3법칙(작용 반작용 법칙)은 힘이 늘 같은 크기, 반대 방향의 쌍으로 작용한다는 법칙이다.",
    source: { title: "Newton's Laws of Motion - NASA Glenn Research Center", url: "https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/newtons-laws-of-motion/" },
  },
  {
    id: "sc-10",
    category: "과학",
    difficulty: "쉬움",
    question: "소리(음파)가 전달될 수 없는 곳은?",
    choices: ["진공", "물속", "쇠막대 속", "공기 중"],
    answer: "진공",
    explanation: "소리는 매질이 있어야 전달되는 역학적 파동이라 매질이 없는 진공에서는 전달되지 않는다.",
    source: { title: "Anatomy of an Electromagnetic Wave - NASA Science", url: "https://science.nasa.gov/ems/02_anatomy/" },
  },
  {
    id: "sc-11",
    category: "과학",
    difficulty: "보통",
    question: "적혈구 속에서 산소와 결합해 온몸으로 산소를 운반하는 단백질은?",
    choices: ["헤모글로빈", "인슐린", "케라틴", "콜라겐"],
    answer: "헤모글로빈",
    explanation: "헤모글로빈은 적혈구 안에 있는 단백질로, 폐에서 산소와 결합해 몸의 조직으로 산소를 나른다.",
    source: { title: "Hemoglobin - MedlinePlus Medical Encyclopedia", url: "https://medlineplus.gov/ency/article/003645.htm" },
  },

  // ===== 예술과 문화 =====
  {
    id: "ac-01",
    category: "예술과 문화",
    difficulty: "쉬움",
    question: "루브르 박물관이 소장한 「모나리자」를 그린 화가는?",
    choices: ["레오나르도 다빈치", "미켈란젤로", "라파엘로", "렘브란트"],
    answer: "레오나르도 다빈치",
    explanation: "「모나리자」는 레오나르도 다빈치의 작품으로, 루브르 박물관이 소장하고 있다.",
    source: { title: "La Joconde (Mona Lisa) - Louvre Collections", url: "https://collections.louvre.fr/en/ark:/53355/cl010062370" },
  },
  {
    id: "ac-02",
    category: "예술과 문화",
    difficulty: "쉬움",
    question: "흔히 '운명 교향곡'이라 불리는 교향곡 제5번 C단조를 작곡한 사람은?",
    choices: ["베토벤", "모차르트", "브람스", "차이콥스키"],
    answer: "베토벤",
    explanation: "베토벤 교향곡 5번의 별명 '운명'은 전기 작가 신들러가 전한 일화에서 나왔다.",
    source: { title: "Symphony no. 5 (C minor) op. 67 - Beethoven-Haus Bonn", url: "https://www.beethoven.de/en/work/view/6260401733894144/Sinfonie+Nr.+5+(c-Moll)+op.+67" },
  },
  {
    id: "ac-03",
    category: "예술과 문화",
    difficulty: "쉬움",
    question: "1888년 프랑스 아를에서 「해바라기」를 그린 화가는?",
    choices: ["빈센트 반 고흐", "폴 고갱", "클로드 모네", "폴 세잔"],
    answer: "빈센트 반 고흐",
    explanation: "반 고흐는 1888년 아를에서 고갱의 방문을 앞두고 집을 꾸미려고 「해바라기」를 그렸다.",
    source: { title: "Sunflowers - The National Gallery, London", url: "https://www.nationalgallery.org.uk/paintings/vincent-van-gogh-sunflowers" },
  },
  {
    id: "ac-04",
    category: "예술과 문화",
    difficulty: "쉬움",
    question: "『햄릿』, 『오셀로』, 『리어왕』, 『맥베스』를 쓴 극작가는?",
    choices: ["셰익스피어", "몰리에르", "괴테", "입센"],
    answer: "셰익스피어",
    explanation: "네 작품 모두 영국 극작가 셰익스피어가 쓴 비극이다.",
    source: { title: "희곡 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0066078" },
  },
  {
    id: "ac-05",
    category: "예술과 문화",
    difficulty: "보통",
    question: "구경꾼들이 둥글게 둘러앉아 두 사람의 겨루기를 지켜보는 모습을 담은 김홍도의 풍속화는?",
    choices: ["씨름", "서당", "무동", "미인도"],
    answer: "씨름",
    explanation: "「씨름」은 김홍도 풍속도 화첩의 한 장면으로, 둘러앉은 구경꾼과 씨름꾼을 생생히 그렸다.",
    source: { title: "김홍도 필 풍속도 화첩 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0013639" },
  },
  {
    id: "ac-06",
    category: "예술과 문화",
    difficulty: "보통",
    question: "1937년 「게르니카」를 그린 화가는?",
    choices: ["파블로 피카소", "살바도르 달리", "호안 미로", "프란시스코 고야"],
    answer: "파블로 피카소",
    explanation: "「게르니카」는 피카소가 1937년 파리에서 그린 작품으로, 레이나 소피아 미술관이 소장한다.",
    source: { title: "Guernica - Museo Nacional Centro de Arte Reina Sofía", url: "https://www.museoreinasofia.es/colecciones/obra/guernica/" },
  },
  {
    id: "ac-07",
    category: "예술과 문화",
    difficulty: "어려움",
    question: "1853년 베네치아 라 페니체 극장에서 초연된 오페라 「라 트라비아타」의 작곡가는?",
    choices: ["주세페 베르디", "자코모 푸치니", "조아키노 로시니", "리하르트 바그너"],
    answer: "주세페 베르디",
    explanation: "「라 트라비아타」는 베르디의 3막 오페라로, 1853년 3월 6일 라 페니체에서 초연되었다.",
    source: { title: "Verdi, La traviata - Teatro La Fenice", url: "https://www.teatrolafenice.it/en/event/giuseppe-verdi-la-traviata/" },
  },
  {
    id: "ac-08",
    category: "예술과 문화",
    difficulty: "보통",
    question: "1969년부터 집필해 1994년에 완간한 대하소설 『토지』의 작가는?",
    choices: ["박경리", "박완서", "조정래", "최명희"],
    answer: "박경리",
    explanation: "박경리는 1969년 집필을 시작해 1994년 『토지』 전 5부 16권을 완간했다.",
    source: { title: "토지 - 한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0059209" },
  },
  {
    id: "ac-09",
    category: "예술과 문화",
    difficulty: "보통",
    question: "'인상주의'라는 이름이 생기는 계기가 된 그림 「인상, 해돋이」를 그린 화가는?",
    choices: ["클로드 모네", "에두아르 마네", "오귀스트 르누아르", "에드가 드가"],
    answer: "클로드 모네",
    explanation: "모네가 붙인 제목 「인상」에서 비평가 르루아가 '인상주의자'라는 말을 만들었다.",
    source: { title: "Impression, soleil levant - Musée Marmottan Monet", url: "https://www.marmottan.fr/en/notice/4014/" },
  },
  {
    id: "ac-10",
    category: "예술과 문화",
    difficulty: "쉬움",
    question: "제92회(2020년) 아카데미 시상식에서 작품상을 받은 한국 영화는?",
    choices: ["기생충", "괴물", "올드보이", "미나리"],
    answer: "기생충",
    explanation: "봉준호 감독의 「기생충」은 2020년 제92회 아카데미 시상식에서 작품상을 받았다.",
    source: { title: "The 92nd Academy Awards (2020) - Oscars.org", url: "https://www.oscars.org/oscars/ceremonies/2020" },
  },
  {
    id: "ac-11",
    category: "예술과 문화",
    difficulty: "보통",
    question: "교황 율리우스 2세의 의뢰로 바티칸 시스티나 성당의 천장화를 그린 화가는?",
    choices: ["미켈란젤로", "라파엘로", "산드로 보티첼리", "티치아노"],
    answer: "미켈란젤로",
    explanation: "미켈란젤로는 1508년 율리우스 2세의 의뢰를 받아 시스티나 성당 천장에 창세기 이야기를 그렸다.",
    source: { title: "The Sistine Chapel - Vatican Museums", url: "https://vatican.museum/the-museum/the-sistine-chapel" },
  },
];
